### ISSUE TITLE
Camera dropping issues

### ISSUE THREAD

**Issue by MickHarrigan** [MickHarrigan/uhdrtz-rust#23]
When re-running the program without disconnecting the camera there is a high chance that the camera cannot be used and gives an error about mutex poisoning.

**Comment by clostoski** [comment]
possibly fixed: switched from callback camera to standard camera.

**Comment by MickHarrigan** [comment]
> possibly fixed: switched from callback camera to standard camera.

The change stated had no real affect on the outcome. The proposed solution is in #97.

This is a workaround mostly, but it should get rid of most (if not all) of the issues.

**Comment by MickHarrigan** [comment]
Addressed in #101
