### ISSUE TITLE
Add image adjustment features

### ISSUE THREAD

**Issue by dancleaver** [MickHarrigan/uhdrtz-rust#42]
Might use [imgproc-rs](https://docs.rs/imgproc-rs/latest/imgproc_rs/) or [image2](https://docs.rs/image2/1.9.2/image2/).

**Comment by dancleaver** [comment]
> One thing for sure that needs to be added is image adjustments (exposure, levels (combined-RGB input black level, gamma, input white level - like the Levels image adjustment in Photoshop) and white balance selection for tungsten and daylight. Basically, we need post-processing controls to make the final image to look as good as possible

**Comment by MickHarrigan** [comment]
Addressed in #91 and its predecessors
