### ISSUE TITLE
Reconnect bluetooth device while the GUI is open

### ISSUE THREAD

**Issue by dancleaver** [MickHarrigan/uhdrtz-rust#45]
This would allow us to reconnect the Arduino without killing and restarting the program.

**Comment by clostoski** [comment]
Is this done?

**Comment by MickHarrigan** [comment]
> Is this done?

No, currently there is no implementation to have the arduino reconnect to the system on a disconnect.

A system would have to be added that detects if the bluetooth connection is dropped, then restart the connection process. This could hook into the gui to have something show if the crank is connected and what data is being received from it.
