### ISSUE TITLE
PC freezes while working on this project

### ISSUE THREAD

**Issue by dancleaver** [MickHarrigan/uhdrtz-rust#59]
My PC had a few freezes happen during the past week. They all occurred while testing the program or shortly thereafter. Mick has also had this happen. One theory is that is has to do with #23 but we don't know for sure yet.

**Comment by dancleaver** [comment]
> Is this happening on the Mini PC or personal PC?

Personal

**Comment by clostoski** [comment]
> > Is this happening on the Mini PC or personal PC?
> 
> Personal

Well if it works fine on the Mini PC then it doesn't matter all that much. We should test to be sure

**Comment by dancleaver** [comment]
My PC has not frozen in a couple weeks. Not sure if it is still an issue.
