### ISSUE TITLE
Sync the camera control sliders with the real current settings

### ISSUE THREAD

**Issue by dancleaver** [MickHarrigan/uhdrtz-rust#85]
I'm thinking we do one of these upon startup:

1. Reset to the defaults
2. Read the current settings from the camera
3. Read settings from a file

**Comment by dancleaver** [comment]
We decided to do number 1 because `VideoStream` does not allow us to read the values from the camera. Currently the api is only to send camera controls and receive video frames.

**Comment by MickHarrigan** [comment]
Addressed with #91
